import type { Product, ProductCategory } from "@/types";

export const CATEGORIES: ProductCategory[] = ["Hat", "Jacket", "Innerwear", "Pants", "Shoes", "Bag"];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "jkt-utility-khaki",
    name: "Utility Work Jacket",
    category: "Jacket",
    color: "Khaki",
    sizes: ["M", "L"],
    price: 8900,
    stock: "In Stock",
    styleTags: ["Workwear", "Casual", "Relaxed"],
    matchScore: 94,
    reason: "Matches the customer’s relaxed workwear style and balances well with navy pants.",
  },
  {
    id: "jkt-denim-oversized",
    name: "Oversized Denim Jacket",
    category: "Jacket",
    color: "Light Blue",
    sizes: ["S", "M", "L"],
    price: 9900,
    stock: "In Stock",
    styleTags: ["Casual", "Street", "Oversized"],
    matchScore: 87,
    reason: "Adds a casual street touch while keeping the silhouette relaxed.",
  },
  {
    id: "jkt-blouson-black",
    name: "Minimal Black Blouson",
    category: "Jacket",
    color: "Black",
    sizes: ["M", "L"],
    price: 11900,
    stock: "Low Stock",
    styleTags: ["Minimal", "Office", "Regular"],
    matchScore: 89,
    reason: "Creates a clean and mature casual look.",
  },

  {
    id: "pnt-relaxed-navy",
    name: "Relaxed Navy Pants",
    category: "Pants",
    color: "Navy",
    sizes: ["M", "L"],
    price: 6900,
    stock: "In Stock",
    styleTags: ["Workwear", "Casual", "Relaxed"],
    matchScore: 91,
    reason: "A relaxed silhouette that keeps the look clean and easy to wear.",
  },
  {
    id: "pnt-wide-tapered-chino",
    name: "Wide Tapered Chino",
    category: "Pants",
    color: "Beige",
    sizes: ["S", "M", "L"],
    price: 7900,
    stock: "In Stock",
    styleTags: ["Workwear", "Office", "Relaxed"],
    matchScore: 88,
    reason: "A wide-tapered cut balances proportions and elevates workwear outfits.",
  },
  {
    id: "pnt-straight-black-denim",
    name: "Straight Black Denim",
    category: "Pants",
    color: "Black",
    sizes: ["M", "L"],
    price: 8900,
    stock: "Low Stock",
    styleTags: ["Street", "Minimal", "Regular"],
    matchScore: 86,
    reason: "A versatile base that keeps the outfit sharp and modern.",
  },

  {
    id: "sh-minimal-black-sneakers",
    name: "Minimal Black Sneakers",
    category: "Shoes",
    color: "Black",
    sizes: ["26cm", "27cm", "28cm"],
    price: 7900,
    stock: "In Stock",
    styleTags: ["Minimal", "Casual", "Workwear"],
    matchScore: 88,
    reason: "Balances workwear elements and works for commuting or weekends.",
  },
  {
    id: "sh-brown-leather-loafers",
    name: "Brown Leather Loafers",
    category: "Shoes",
    color: "Brown",
    sizes: ["25cm", "26cm", "27cm", "28cm"],
    price: 12900,
    stock: "In Stock",
    styleTags: ["Office", "Minimal", "Regular"],
    matchScore: 84,
    reason: "A smart upgrade that adds mature polish with minimal effort.",
  },
  {
    id: "sh-white-court-sneakers",
    name: "White Court Sneakers",
    category: "Shoes",
    color: "White",
    sizes: ["25cm", "26cm", "27cm", "28cm", "29cm"],
    price: 8900,
    stock: "In Stock",
    styleTags: ["Casual", "Minimal", "Regular"],
    matchScore: 85,
    reason: "Brightens the outfit while keeping it clean and approachable.",
  },

  {
    id: "hat-knit-beanie-black",
    name: "Compact Knit Beanie",
    category: "Hat",
    color: "Black",
    sizes: ["One Size"],
    price: 2900,
    stock: "In Stock",
    styleTags: ["Street", "Casual", "Minimal"],
    matchScore: 82,
    reason: "Adds a subtle street touch without overwhelming the look.",
  },
  {
    id: "hat-nylon-cap-khaki",
    name: "Nylon Utility Cap",
    category: "Hat",
    color: "Khaki",
    sizes: ["One Size"],
    price: 3200,
    stock: "In Stock",
    styleTags: ["Workwear", "Casual"],
    matchScore: 86,
    reason: "Reinforces the workwear direction and feels practical for daily wear.",
  },
  {
    id: "hat-minimal-bucket-beige",
    name: "Minimal Bucket Hat",
    category: "Hat",
    color: "Beige",
    sizes: ["One Size"],
    price: 3500,
    stock: "Low Stock",
    styleTags: ["Casual", "Minimal", "Relaxed"],
    matchScore: 83,
    reason: "Softens the palette and matches relaxed silhouettes.",
  },

  {
    id: "inr-tee-offwhite",
    name: "Heavyweight Tee (Off-white)",
    category: "Innerwear",
    color: "Off-white",
    sizes: ["S", "M", "L"],
    price: 3900,
    stock: "In Stock",
    styleTags: ["Minimal", "Casual", "Regular"],
    matchScore: 90,
    reason: "A clean base layer that keeps the outfit crisp and easy to style.",
  },
  {
    id: "inr-oxford-shirt-navy",
    name: "Soft Oxford Shirt",
    category: "Innerwear",
    color: "Navy",
    sizes: ["S", "M", "L"],
    price: 5900,
    stock: "In Stock",
    styleTags: ["Office", "Workwear", "Regular"],
    matchScore: 86,
    reason: "Bridges workwear and office tones while staying relaxed.",
  },
  {
    id: "inr-knit-polo-gray",
    name: "Fine Knit Polo",
    category: "Innerwear",
    color: "Gray",
    sizes: ["M", "L"],
    price: 6900,
    stock: "Low Stock",
    styleTags: ["Minimal", "Office", "Slim"],
    matchScore: 84,
    reason: "Adds a refined texture and looks premium under outerwear.",
  },

  {
    id: "bag-nylon-crossbody-black",
    name: "Nylon Crossbody Bag",
    category: "Bag",
    color: "Black",
    sizes: ["One Size"],
    price: 5900,
    stock: "In Stock",
    styleTags: ["Workwear", "Street", "Casual"],
    matchScore: 87,
    reason: "Keeps hands free and complements utility-inspired styling.",
  },
  {
    id: "bag-leather-tote-brown",
    name: "Structured Leather Tote",
    category: "Bag",
    color: "Brown",
    sizes: ["One Size"],
    price: 14900,
    stock: "In Stock",
    styleTags: ["Office", "Minimal"],
    matchScore: 83,
    reason: "A premium upsell that elevates the entire look instantly.",
  },
  {
    id: "bag-canvas-shopper-khaki",
    name: "Canvas Shopper Bag",
    category: "Bag",
    color: "Khaki",
    sizes: ["One Size"],
    price: 4900,
    stock: "Low Stock",
    styleTags: ["Casual", "Workwear", "Relaxed"],
    matchScore: 85,
    reason: "Echoes khaki tones and keeps the overall styling light.",
  },
];

